title: Site
tabs:
  content:
    label: Content
    columns:
      - width: 2/3
        sections:
          works: sections/works
      - width: 1/3
        sections: 
          pages:
            type: pages
            status: listed
            parent: site
            info: "{{ page.description }}"
  options:
    columns:
      - width: 1/2
        fields:
          description:
            type: textarea
            icon: title
          additionalDescription:
            type: textarea
            icon: title  
          behanceID:
            type: text
            icon: title
          image:
            type: files
            layout: list
            info: "{{ file.dimensions }}"
            image:
              ratio: 5/4
              cover: true
            size: small  
      - width: 1/2
        fields:
          social:
            label: Profiles
            type: structure
            fields:
              platform:
                type: text
              link:
                type: url
          email:
            type: email
            width: 1/2
          emailPress:
            type: email
            width: 1/2
          phone:
            type: tel
            width: 1/2
          popUpImage:
            type: files
            layout: list
            info: "{{ file.dimensions }}"
            image:
              ratio: 5/4
              cover: true
            size: small   