title: Site
tabs:
  content:
    label: Content
    columns:
      - width: 2/3
        sections:
          works: sections/works
      - width: 1/3
        sections: 
          pages:
            type: pages
            status: listed
            parent: site
            info: "{{ page.description }}"
  info:
    label: Info          
          